### ISSUE TITLE
Feature: Alternate method to view guides

### ISSUE THREAD

**Issue by James-Monkey** [BitsOfAByte/KikoGuide#17]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### New or Existing?

Improvement to existing feature

### Summary of your suggestion.

Currently the ability to view guides is tied to 2 methods. Either having completed the quest that unlocks the Dungeon. Or if you character is in the location that matches the TerritoryID of the guide. (Clearing the dungeon is a part of the quest completion conditions. So you actually have to clear the content and then hand in the quest for it to show up in the guides.)

I would guess that in the future there will be a toggle for viewing all the guides, regardless of those conditions. So I won't talk about that.

My request is if there is any way for the guides to unlock on quest pickup rather than quest completion.

From making a guide and getting a grasp of what the JSON is targetting, I could see a potential way around this by just simple changing the UnlockQuestID to target the previous quest on that chain. Unlocking the guide 1 quest before. Not the cleanest method, but if the functionality is not on the API, it is a dirty solution.

### Why should this be added or changed?

This will allow the player to skim over the guide before they head in. Rather than trying to keep up with Usain Bolt the tank while trying to read the guide.

This would still be spoiler free as by that point you know what the dungeon is called. As the quest you are on at that time is for you to actual clear said content.

Thanks!

**Comment by BitsOfAByte** [comment]
This can be easily achieved as there is an available method to check if a player has a quest ID in their active quests in the `QuestManager` already. This was originally the intention for showing duties in the list but it was changed because of certain quests that will unlock multiple duties, I did not want to spoil all duties associated with the quest

However showing it before going in does also sound like a good reason for changing this behaviour back

**Comment by BitsOfAByte** [comment]
Now uses the old method for checking if a duty is unlocked (78a950cc8aaec8e5ab9c57925790919f00a924fe). I will keep an eye on this and see if it garners any complaints
