### ISSUE TITLE
6.3 Update

### ISSUE THREAD

**Issue by ichi-obi** [BitsOfAByte/KikoGuide#39]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### Issue

This plugin needs update for 6.3.

**Comment by BitsOfAByte** [comment]
It's not very likely to be updated until I can dedicate time to finishing it, the plugin as it was released was unfinished and messy and lacked guides for anything other than ARR dungeons.
